config/routes.rb
Market::Application.routes.draw do

  devise_for :users

  root :to => "pages#home"
  match 'portfolio' => "users#portfolio", :as => :portfolio
  match 'faq' => "pages#faq"
  resources :options
  resources :withdrawal_requests
  resources :currencies
  resources :futures
  match "options/expires/:year/:month" => "options#expires", :as => :options_expires
  match "/account_funding" => "users#account_funding", :as => :account_funding
  match "/notify" => "users#notify", :as => :mtgox_notify

  resources :trades

end

app/models/currency.rb
class Currency < ActiveRecord::Base
    has_many :trades, :foreign_key => "instrument_id", :conditions => {:instrument => "Currency"}
    has_many :transactions, :foreign_key => "instrument_id", :conditions => {:instrument => "Currency"}

    def best_bid
        trades.bids.order('price desc').first.price if trades.bids.order('price desc').first
    end

    def best_ask
        trades.asks.order('price asc').first.price if trades.asks.order('price asc').first
    end

end

# == Schema Information
#
# Table name: currencies
#
#  id            :integer         not null, primary key
#  name          :string(255)
#  value         :decimal(, )
#  created_at    :datetime
#  updated_at    :datetime
#  open_interest :integer         default(0)
#

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController

    def index
        @currencies = Currency.all
    end

    def show
        @instrument = Currency.find(params[:id])
        @trade = Trade.new
        render 'trades/new'
    end

end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/index.html.erb
<h2>Available currencies:</h2>

<table id="currencies">
    <tr>
        <th> Name </th>
        <th> Best bid </th>
        <th> Best Ask </th>
        <th> Last price </th>
        <th> Trade </th>
    </tr>
    <% @currencies.each do |c| %>
        <tr>
            <td> <%= link_to "BTC/#{c.name.upcase}", c %> </td>
            <td> <%= c.best_bid %> </td>
            <td> <%= c.best_ask %> </td>
            <td> <%= c.value %> </td>
            <td> <%= link_to "Trade", new_trade_path(:i => "currency", :id => c.id) %>
        </tr>
    <% end %>
</table>