config/routes.rb
Market::Application.routes.draw do

  devise_for :users

  root :to => "pages#home"
  match 'portfolio' => "users#portfolio", :as => :portfolio
  match 'faq' => "pages#faq"
  resources :options
  resources :withdrawal_requests
  resources :currencies
  resources :futures
  match "options/expires/:year/:month" => "options#expires", :as => :options_expires
  match "/account_funding" => "users#account_funding", :as => :account_funding
  match "/notify" => "users#notify", :as => :mtgox_notify

  resources :trades

end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
    has_one :portfolio
    has_many :withdrawal_requests
    has_many :bought, :class_name => 'Transaction', :foreign_key => "buyer_id"
    has_many :sold, :class_name => 'Transaction', :foreign_key => "seller_id"
    has_many :trades
    has_many :positions, :through => :portfolio

    devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable

    # Setup accessible (or protected) attributes for your model
    attr_accessible :email, :password, :password_confirmation, :remember_me

    delegate :create_or_update_position, :to => :portfolio
    delegate :remove_from_position, :to => :portfolio
    

    after_create :create_portfolio
    #Asynchronous with delayed job

    def make_currency_trade(trade)
        instrument = trade.instrument.classify.constantize.find(trade.instrument_id)
        #make sure you have what you are selling
        if trade.typ == "ask"
            if portfolio.usd >= trade.amount
                trade.save
                "Trade executed."
            else 
                "You do not have sufficient USD to sell."
            end
        elsif trade.typ == "bid"
            if portfolio.funds >= trade.amount*trade.price
                trade.save
                "Trade executed. Check portfolio page."
            else
                "You do not have sufficient funds."
            end
        end
    end

    def make_trade(trade)
        #for option trade only
        trade.user = self
        if trade.instrument == "Currency"
            make_currency_trade(trade)
        elsif trade.instrument == "Option"
            make_option_trade(trade)
        else
            "Invalid instrument "
        end
        #spawn tradeexecutor in new thread
    end


    def make_option_trade(trade)
        option = trade.instrument.classify.constantize.find(trade.instrument_id)
        if option.typ == "call"
            if trade.typ == "bid"
                if portfolio.funds > trade.amount*trade.price
                    trade.save
                    "Trade executed. Check your portfolio page to see pending orders."
                else 
                    "You do not have sufficient funds."
                end
            elsif trade.typ == "ask"
                if portfolio.usd > trade.amount
                    trade.save
                    "Trade executed. Check your portfolio page to view pending orders."
                else
                    "You cannot write calls without covering your total position. You need at least
                    #{trade.amount}USD in your account."
                end
            end
        elsif option.typ == "put"
            if trade.typ == "bid"
                if portfolio.funds > trade.amount*trade.price
                    trade.save
                    "Trade executed. Check portfolio page to see pending orders."
                else
                    "You do not have sufficient funds. You need #{trade.amount*trade.price}BTC"
                end
            elsif trade.typ = "ask"
                if portfolio.funds > trade.amount*option.strike
                    trade.save
                    "Trade executed. Check portfolio page to see pending orders"
                else
                    "You do not have sufficient funds to cover you put. You need at least 
                    #{option.strike*trade.amount}BTC in your account to cover your position."
                end
            end
        end
    end


    private

    def create_portfolio
        Portfolio.create!(:user_id => id, :funds => 0.0)
    end

end


# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(128)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_filter :authenticate_user!, :only =>[:portfolio, :account_funding]

    def portfolio
        @portfolio = current_user.portfolio
    end

    def account_funding
        @withdrawal = WithdrawalRequest.new
    end

    def notify
        txn = params[:txn_id]
        user = User.find_by_id(params[:custom])
        amount = params[:amount]
        cc = params[:currency_code]
        if verify(txn, amount) == "ok"
            if cc == "USD"
                c = Currency.find_by_name("USD")
                portfolio =  user.portfolio.positions.find_or_create_by_instrument("Currency") {|p| p.instrument_id = c.id}
                portfolio.increment!(:amount, amount.to_d)
            elsif cc == "BTC"
                user.portfolio.funds.increment!(amount)
            end
        end
    end

    def verify(txn,amount, merch_id = "12043")
        uri = URI.parse("https://mtgox.com/code/gateway/checkTxn.php")
        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = true
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE
        request = Net::HTTP::Post.new(uri.request_uri, {'txn_id' => txn, 'merchID' => merch_id, 'amount' => amount})

        response = http.request(request)
        puts response.body
        response.body
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_pending.html.erb
<p> Pending Orders </p>
<table id="orders">
    <tr>
        <th> Name</th>
        <th> Type </th>
        <th> Amount </th>
        <th> Price </th>
        <th> Total </th>
        <th> Action </th>
    </tr>
    <% current_user.trades.each do |t| %>
        <% i = t.instrument.classify.constantize.find(t.instrument_id) %>
        <tr> 
            <td><%=link_to i.name, i %></td>
            <td><%=t.typ %> </td>
            <td><%=t.amount%> </td>
            <td><%=t.price%> </td>
            <td><%=t.price * t.amount%> </td>
            <td><%= link_to "Edit", edit_trade_path(t) %> | <%= link_to "Cancel", trade_path(t), :confirm => "Are you
                sure you want to cancel the pending order?", :method => :delete %>
            </tr>
        <% end %>
    </table>

app/views/users/_positions.html.erb
    <p> Current positions </p>
    <table id="positions">
        <tr>
            <th> Name</th>
            <th> Type </th>
            <th> Amount </th>
            <th> Market Value </th>
            <th> Total </th>
        </tr>
        <% current_user.positions.each do |t| %>
            <% i = t.instrument.classify.constantize.find(t.instrument_id) %>
            <tr> 
                <td><%=link_to i.name, i %></td>
                <td><%=t.typ %> </td>
                <td><%=t.amount%> </td>
                <td><%=i.value %> </td>
                <td><%=i.value * t.amount%> </td>
            </tr>
        <% end %>
    </table>

app/views/users/_transactions.html.erb
    <p> Last 5 transactions </p>
    <table id="log">
        <tr>
            <th> Name</th>
            <th> Type </th>
            <th> Amount </th>
            <th> Price </th>
            <th> Total </th>
        </tr>
        <% current_user.bought.each do |t| %>
            <% i = t.instrument.classify.constantize.find(t.instrument_id) %>
            <tr> 
                <td><%=link_to i.name, i%></td>
                <td><%=t.typ %> </td>
                <td><%=t.amount%> </td>
                <td><%=t.price%> </td>
                <td><%=t.price * t.amount%> </td>
            </tr>
        <% end %>
    </table>

app/views/users/account_funding.html.erb
<div class="span-12">
    <h3> Add Funds:</h3>
    <h4> Funds can be added instantly from an existing MtGox account </h4>

    <% [1, 5, 10, 20, 50, 100, 200].each do |p| %>
        <form action="https://mtgox.com/merch/checkout" method="post" > 
            <input type="hidden" name="notify_url" value="<%= root_url + "notify" %>"> 
            <input type="hidden" name="business" value="bitoptions"> 
            <input type="hidden" name="currency_code" value="BTC">  
            <input type="hidden" name="item_name" value="BitLeverage Account Funding for <%= current_user.email %>">
            <input type="hidden" name="custom" value="<%= current_user.id %>" >
            <input type="hidden" name="amount" value="<%= p %>"> 
            <input type="hidden" name="return" value="<%= root_url + "account_funding" %>">
            <input type="submit" value="Add <%= p  %>BTC from Mt Gox" /> 
        </form>
        <br>
    <% end %>
</div>

<div class="span-12 last">
    <h3> Withdraw funds: </h3>
    <h4>Withdrawal can be made to a MtGox account, or to a Bitcoin address:</h4>
    <div id="withdraw_details">
        Current account funds:  <%= current_user.portfolio.funds %> BTC <br>
        Amount available to withdraw: <%=  current_user.portfolio.funds - current_user.portfolio.funds_in_margin %> BTC
    </div>



    <%= semantic_form_for @withdrawal do |f| %>
        <%= f.inputs "Withdraw funds" do %>
            <p> BitCoin withdrawals might take anywhere from 10-60 minutes to show up in your account.  </p>
            <%= f.input :typ, :label => "Withdraw to:", :as => :radio, :collection => [["MtGox account", "mtgox"], ["Bitcoin address", "bitcoin"]] %>
            <%= f.input :address, :hint => "Mtgox username or BitCoin address" %>
            <%= f.input :funds, :hint => "Amount to withdraw (BTC)" %>
        <% end %>
        <%= f.buttons do %>
            <%= f.commit_button "Withdraw" %>
        <% end %>
    <% end %>
</div>

app/views/users/portfolio.html.erb
<div id="portfolio">
    <p>BTC Balance: <%= @portfolio.funds %> BTC</p>
    <p>Value of positions: <%= @portfolio.value %> BTC</p>

    <%= render :partial => "pending" %>
    <%= render :partial => "positions" %>


</div>