config/routes.rb
Market::Application.routes.draw do

  devise_for :users

  root :to => "pages#home"
  match 'portfolio' => "users#portfolio", :as => :portfolio
  match 'faq' => "pages#faq"
  resources :options
  resources :withdrawal_requests
  resources :currencies
  resources :futures
  match "options/expires/:year/:month" => "options#expires", :as => :options_expires
  match "/account_funding" => "users#account_funding", :as => :account_funding
  match "/notify" => "users#notify", :as => :mtgox_notify

  resources :trades

end

app/views/shared/_header.html.erb
<div id="header">
    <div class="container">
        <div class="span-8"> 
            <div class="span-8 last title"><%= link_to "BitLeverage", root_path %></div>
            <div class="span-8 last desc">A bitcoin derivatives market.</div>
        </div>
        <div class="span-16 last">
            <%= link_to "Home", root_path %> |
            <%= link_to "Options", options_path %> |
            <%= link_to "Futures", futures_path %> |
            <%= link_to "Currencies", currencies_path %> |
            <%= link_to "FAQ", faq_path %> |
            <% if user_signed_in? %>
                <%= link_to "Portfolio", portfolio_path , :class => "special"%> | 
                <%= link_to "Funds", account_funding_path , :class => "special"%> |
                <%= link_to "Sign Out", destroy_user_session_path , :class => "special"%>
            <% else %>
                <%= link_to "Log In", new_user_session_path, :class => "special"%> |
                <%= link_to "Sign Up", new_user_registration_path, :class => "special"%>
            <% end %>
        </div>
    </div>
</div>